name: ESPHome Impulse Cover Component

about: A comprehensive ESPHome component for impulse-controlled covers with partial opening support

website: https://github.com/AntorFr/esphome-impulse-cover

default_branch: main

visibility: public

# Features
has_issues: true
has_projects: true
has_wiki: true
has_pages: false
has_downloads: true

# Merge options
allow_squash_merge: true
allow_merge_commit: true
allow_rebase_merge: true
delete_branch_on_merge: true

# Issues
has_vulnerability_alerts: true

# Security
security_and_analysis:
  secret_scanning:
    status: enabled
  secret_scanning_push_protection:
    status: enabled

# Repository topics
topics:
  - esphome
  - cover
  - impulse
  - esp32
  - esp8266
  - gate-control
  - home-automation
  - iot
  - partial-opening
  - binary-sensors
