esphome:
  name: clean-test
  friendly_name: Clean Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome

wifi:
  ssid: "test-network"
  password: "test1234"
  ap:
    ssid: "Clean Test Fallback"
    password: "test1234"

captive_portal:

external_components:
  - source: 
      type: local
      path: components
    components: [ impulse_cover ]

output:
  - platform: gpio
    pin: GPIO13  # Non-strapping pin
    id: clean_output

cover:
  - platform: impulse_cover
    name: "Clean Gate"
    id: clean_gate
    output: clean_output
    open_duration: 10s
    close_duration: 10s
