# Configuration pour Black (Python formatter)
[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # Directories to exclude
  \.git
  | \.venv
  | venv
  | build
  | dist
  | __pycache__
)/
'''

# Configuration pour isort (import sorting)
[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_esphome = ["esphome"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "ESPHOME", "FIRSTPARTY", "LOCALFOLDER"]
