esphome:
  name: simple-test
  friendly_name: Simple Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:
ota:

wifi:
  ssid: "test-network"
  password: "test1234"
  ap:
    ssid: "Simple Test Fallback"
    password: "test1234"

captive_portal:

# Import the custom component
external_components:
  - source: 
      type: local
      path: components
    components: [ impulse_cover ]

# Minimal configuration without sensors
output:
  - platform: gpio
    pin: GPIO12  # Using a non-strapping pin
    id: simple_output

cover:
  - platform: impulse_cover
    name: "Simple Gate"
    id: simple_gate
    output: simple_output
    open_duration: 10s
    close_duration: 10s
