esphome:
  name: test-automation-cover
  friendly_name: Test Automation Cover

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: "test-network"
  password: "test1234"

  # Enable fallback hotspot
  ap:
    ssid: "Test Fallback"
    password: "test1234"

captive_portal:

# Import the custom component (local path for testing)
external_components:
  - source:
      type: local
      path: ./components
    components: [ impulse_cover ]

# GPIO Output for sending pulses
output:
  - platform: gpio
    pin: GPIO2
    id: test_gate_output

# Main cover configuration for testing
cover:
  - platform: impulse_cover
    name: "Test Gate"
    id: test_gate

    # Required: Output for sending pulses
    output: test_gate_output

    # Required: Timing configuration
    open_duration: 15s
    close_duration: 15s

    # Simple automation test - just one trigger
    on_open:
      - logger.log: "Gate is opening"
