name: Bug Report
description: Report a bug or issue with the Impulse Cover component
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - AntorFR

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and
        reproduce the issue.

  - type: checkboxes
    id: pre-checks
    attributes:
      label: Pre-flight Checks
      description: Please confirm you have completed these steps
      options:
        - label: I have read the [README.md](../README.md) documentation
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I have tested with the latest version of the component
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure ESPHome with...
        2. Upload to device...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The cover should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, the cover...
    validations:
      required: true

  - type: dropdown
    id: component-type
    attributes:
      label: Component Configuration
      description: Which configuration are you using?
      options:
        - Basic configuration (no sensors)
        - With binary sensors
        - Partial opening configuration
        - Custom configuration
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which microcontroller platform?
      options:
        - ESP8266
        - ESP32
        - ESP32-C3
        - ESP32-S2
        - ESP32-S3
        - Other
    validations:
      required: true

  - type: input
    id: esphome-version
    attributes:
      label: ESPHome Version
      description: What version of ESPHome are you using?
      placeholder: "2025.7.4"
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your ESPHome YAML configuration (remove sensitive data)
      render: yaml
      placeholder: |
        esphome:
          name: my-cover

        impulse_cover:
          - platform: impulse_cover
            name: "Gate"
            # ... rest of config
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output (use `esphome logs your-config.yaml`)
      render: text
      placeholder: |
        [12:34:56][D][impulse_cover:123]: Debug message...
        [12:34:57][E][impulse_cover:456]: Error message...

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Setup
      description: Describe your hardware setup
      placeholder: |
        - Microcontroller: ESP32 DevKit
        - Gate motor: ...
        - Power supply: ...
        - Wiring: GPIO X connected to...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: This issue started after...
