esphome:
  name: advanced-gate-test
  friendly_name: Advanced Gate Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

wifi:
  ssid: "test-network"
  password: "test1234"
  ap:
    ssid: "Advanced Gate Fallback"
    password: "test1234"

captive_portal:

# Import the custom component
external_components:
  - source:
      type: local
      path: ../components
    components: [ impulse_cover ]

# GPIO Outputs
output:
  - platform: gpio
    pin: GPIO2
    id: gate_output
  - platform: gpio
    pin: GPIO25
    id: status_led_output

# Endstop sensors with different logic types
binary_sensor:
  # Example: Reed switch sensor (active HIGH when magnet is present)
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    name: "Gate Open Reed Switch"
    id: gate_open_reed
    device_class: opening

  # Example: Limit switch sensor (active LOW when pressed)
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
    name: "Gate Close Limit Switch"
    id: gate_close_limit
    device_class: opening

cover:
  - platform: impulse_cover
    name: "Advanced Gate"
    id: advanced_gate

    # Required: Output and timing
    output: gate_output
    open_duration: 18s
    close_duration: 16s

    # Optional: Safety and pulse timing
    pulse_delay: 750ms
    safety_timeout: 45s
    safety_max_cycles: 3

    # Endstop sensors with different logic
    open_sensor: gate_open_reed
    close_sensor: gate_close_limit
    open_sensor_inverted: false   # Reed switch is active HIGH
    close_sensor_inverted: true   # Limit switch is active LOW (pressed = LOW)

# Status LED to show gate state
light:
  - platform: binary
    name: "Gate Status LED"
    output: status_led_output
