esphome:
  name: simple-test
  friendly_name: Simple Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome

wifi:
  ssid: "test-network"
  password: "test1234"
  ap:
    ssid: "Simple Test Fallback"
    password: "test1234"

captive_portal:

# Import the custom component
external_components:
  - source: 
      type: local
      path: ../components
    components: [ impulse_cover ]

# Minimal configuration without sensors
output:
  - platform: gpio
    pin: GPIO2  # Using a safe pin
    id: simple_output

# Example sensors (commented out for minimal test)
# binary_sensor:
#   - platform: gpio
#     pin: 
#       number: GPIO14
#       mode: INPUT_PULLUP
#     name: "Gate Open Sensor"
#     id: gate_open_sensor
#     
#   - platform: gpio
#     pin:
#       number: GPIO27
#       mode: INPUT_PULLUP  
#     name: "Gate Close Sensor"
#     id: gate_close_sensor

cover:
  - platform: impulse_cover
    name: "Simple Gate"
    id: simple_gate
    output: simple_output
    open_duration: 10s
    close_duration: 10s
    
    # Optional sensor configuration (commented for minimal test)
    # open_sensor: gate_open_sensor
    # close_sensor: gate_close_sensor
    # open_sensor_inverted: true    # Example: active LOW sensor
    # close_sensor_inverted: false  # Example: active HIGH sensor
