esphome:
  name: partial-opening-test
  friendly_name: Partial Opening Test

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
api:

ota:
  - platform: esphome

wifi:
  ssid: "test-network"
  password: "test1234"
  ap:
    ssid: "Partial Test Fallback"
    password: "test1234"

captive_portal:

# Import the custom component
external_components:
  - source:
      type: local
      path: ../components
    components: [ impulse_cover ]

# Configuration with custom timings for partial opening
output:
  - platform: gpio
    pin: GPIO2  # Control pin for gate motor
    id: gate_output

# Optional end-stop sensors for precise positioning
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
    name: "Gate Open Sensor"
    id: gate_open_sensor

  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
    name: "Gate Close Sensor"
    id: gate_close_sensor

cover:
  - platform: impulse_cover
    name: "Gate with Partial Opening"
    id: partial_gate
    output: gate_output

    # Custom timings - adjust these to match your gate
    open_duration: 20s    # Time for full opening (0% to 100%)
    close_duration: 18s   # Time for full closing (100% to 0%)

    # Pulse timing - time between control pulses
    pulse_delay: 800ms    # Slightly longer for more reliable operation

    # Safety settings
    safety_timeout: 90s   # Stop after 90 seconds if no endstop
    safety_max_cycles: 3  # Max 3 operation cycles before safety stop

    # End-stop sensors for precise positioning
    open_sensor: gate_open_sensor
    close_sensor: gate_close_sensor
    open_sensor_inverted: true     # Active LOW sensor (pullup)
    close_sensor_inverted: true    # Active LOW sensor (pullup)

# Example automation for partial opening scenarios
automation:
  # Partial opening to 30% (for pedestrian access)
  - id: pedestrian_open
    trigger:
      - platform: api
        service: pedestrian_open
    action:
      - cover.control:
          id: partial_gate
          position: 0.3  # 30% open

  # Partial opening to 70% (for small vehicles)
  - id: small_vehicle_open
    trigger:
      - platform: api
        service: small_vehicle_open
    action:
      - cover.control:
          id: partial_gate
          position: 0.7  # 70% open

  # Full opening for large vehicles
  - id: full_open
    trigger:
      - platform: api
        service: full_open
    action:
      - cover.control:
          id: partial_gate
          position: 1.0  # 100% open (fully open)

  # Quick close
  - id: quick_close
    trigger:
      - platform: api
        service: quick_close
    action:
      - cover.control:
          id: partial_gate
          position: 0.0  # 0% open (fully closed)

# Web server for easy control
web_server:
  port: 80
